/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;
import abd.p1.controller.Controlador;
import abd.p1.model.Genero;
import abd.p1.model.Usuario;
import com.toedter.calendar.JDateChooser;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jhersy
 */
public class EdicionUsuario extends javax.swing.JDialog {
    private boolean cancelar;
    
    private Controlador ctrl;
    private Usuario user;
    private String cambiaNombre;
    private Date cambiaFecha;
    private byte[] cambiaAvatar;
    private Genero cambiaGenero;
    private Genero cambiaPreferencia;    
    private DefaultListModel listaModel = new DefaultListModel();
    private List<String> aficiones = new ArrayList<String>();
    /**
     * Creates new form EdicionUsuario
     */
    public EdicionUsuario(java.awt.Frame parent, boolean modal, Controlador ctrl, Usuario user) {
        super(parent, modal);
        initComponents();
        this.ctrl = ctrl;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonCambiarNombre = new javax.swing.JButton();
        ButtonCambiarFechaNacimiento = new javax.swing.JButton();
        ButtonCambiarAvatar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaAficiones = new javax.swing.JList<>();
        ButtonAddAficion = new javax.swing.JButton();
        ButtonEliminarAficion = new javax.swing.JButton();
        ButtonEditarAficion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelSexo = new javax.swing.JLabel();
        LabelBusca = new javax.swing.JLabel();
        ButtonCambiarSexo = new javax.swing.JButton();
        ButtonCambiarPreferencia = new javax.swing.JButton();
        LabelNombre = new javax.swing.JLabel();
        LabelEdad = new javax.swing.JLabel();
        ButtonCambiarContraseña = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();
        ButtonGuardarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonCambiarNombre.setText("Cambiar nombre");
        ButtonCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarNombreActionPerformed(evt);
            }
        });

        ButtonCambiarFechaNacimiento.setText("Cambiar fecha de nacimiento");
        ButtonCambiarFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarFechaNacimientoActionPerformed(evt);
            }
        });

        ButtonCambiarAvatar.setText("Cambiar avatar");
        ButtonCambiarAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarAvatarActionPerformed(evt);
            }
        });

        jLabel1.setText("Descripción");

        textAreaDescripcion.setColumns(20);
        textAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(textAreaDescripcion);

        jLabel2.setText("Aficiones");

        ListaAficiones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaAficiones);

        ButtonAddAficion.setText("Añadir afición");
        ButtonAddAficion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddAficionActionPerformed(evt);
            }
        });

        ButtonEliminarAficion.setText("Eliminar seleccionada");
        ButtonEliminarAficion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarAficionActionPerformed(evt);
            }
        });

        ButtonEditarAficion.setText("Editar seleccionada");
        ButtonEditarAficion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarAficionActionPerformed(evt);
            }
        });

        jLabel3.setText("Sexo: ");

        jLabel4.setText("Busca: ");

        LabelSexo.setText("Masculino");

        LabelBusca.setText("Mujeres");

        ButtonCambiarSexo.setText("Cambiar sexo");
        ButtonCambiarSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarSexoActionPerformed(evt);
            }
        });

        ButtonCambiarPreferencia.setText("Cambiar preferencia");
        ButtonCambiarPreferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarPreferenciaActionPerformed(evt);
            }
        });

        LabelNombre.setText("Nombre");

        LabelEdad.setText("Edad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(LabelEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonCambiarFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCambiarNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCambiarAvatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelBusca)
                                            .addComponent(LabelSexo))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonAddAficion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonEliminarAficion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(ButtonEditarAficion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCambiarSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCambiarPreferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCambiarNombre)
                    .addComponent(LabelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelEdad)
                    .addComponent(ButtonCambiarFechaNacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCambiarAvatar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonAddAficion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEliminarAficion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEditarAficion))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(LabelSexo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(LabelBusca)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonCambiarSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCambiarPreferencia)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ButtonCambiarContraseña.setText("Cambiar contraseña");

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonGuardarCambios.setText("Guardar cambios");
        ButtonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonCambiarContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonGuardarCambios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCambiarContraseña)
                    .addComponent(ButtonCancelar)
                    .addComponent(ButtonGuardarCambios))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarNombreActionPerformed
        // TODO add your handling code here:
        JDialog cambiarNombre = new JDialog(this, true);
        cambiaNombre = JOptionPane.showInputDialog(cambiarNombre, "Editar nombre");
        LabelNombre.setText(cambiaNombre);
        System.out.println(cambiaNombre);
    }//GEN-LAST:event_ButtonCambiarNombreActionPerformed

    private void ButtonCambiarFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarFechaNacimientoActionPerformed
        JDialog dialog = new JDialog(this, true);
        dialog.setBounds(200, 200, 400, 150);
        JPanel panel = new JPanel();
        JDateChooser fecha = new JDateChooser();
        panel.add(fecha);
        JButton aceptar = new JButton("Aceptar");
        panel.add(aceptar);
        dialog.add(panel);
        dialog.setVisible(true);
        System.out.println("vista");
        System.out.println(fecha.getDate().toString());
        aceptar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cambiaFecha = fecha.getDate();
                System.out.println(cambiaFecha);
                dialog.setVisible(false);            
            }
        });

    }//GEN-LAST:event_ButtonCambiarFechaNacimientoActionPerformed

    private void ButtonCambiarAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarAvatarActionPerformed
        JDialog frame = new JDialog(this, true);
        frame.setBounds(0, 0, 600, 400);
        JPanel panel = new JPanel();
        JFileChooser avatar = new JFileChooser();
        avatar.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG","jpg","png");
        avatar.setFileFilter(filtro);
        panel.add(avatar);
        JButton aceptar = new JButton("Aceptar");
        panel.add(aceptar);
        frame.add(panel);
        frame.setVisible(true);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageIcon cambiaImagen = new ImageIcon(avatar.getSelectedFile().toString());
                // falta pasar a array de bytes
                frame.setVisible(false);
            }
        });
    }//GEN-LAST:event_ButtonCambiarAvatarActionPerformed

    private void ButtonAddAficionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddAficionActionPerformed
        JDialog addAficion = new JDialog(this, true);
        String nuevaAficion = JOptionPane.showInputDialog(addAficion, "Introduce nueva afición: ");
        aficiones.add(nuevaAficion);
        listaModel.addElement(nuevaAficion);
        ListaAficiones.setModel(listaModel);
    }//GEN-LAST:event_ButtonAddAficionActionPerformed

    private void ButtonEditarAficionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarAficionActionPerformed
        JDialog addAficion = new JDialog(this, true);
        String nuevaAficion = JOptionPane.showInputDialog(addAficion, "Editar esta afición: ");
        int index = ListaAficiones.getSelectedIndex();
        System.out.println("Vas a cambiar en la pos " + index);
        listaModel.remove(index); 
        aficiones.add(index, nuevaAficion);
        listaModel.add(index, nuevaAficion);
        ListaAficiones.setModel(listaModel);
    }//GEN-LAST:event_ButtonEditarAficionActionPerformed

    private void ButtonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarCambiosActionPerformed
        user.setNombre(cambiaNombre);
        user.setFecha_nac(cambiaFecha);
        //user.setFoto(cambiaAvatar.);
        user.setGenero(cambiaGenero);
        user.setBusca(cambiaPreferencia);
        user.setAficiones(aficiones);
        user.setDescripcion(textAreaDescripcion.getText());
        this.setVisible(false);

    }//GEN-LAST:event_ButtonGuardarCambiosActionPerformed

    private void ButtonCambiarSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarSexoActionPerformed
       JDialog dialog = new JDialog(this, true);
       dialog.setBounds(500, 60, 350, 80);
       JPanel cambiarPreferencia = new JPanel();
       JButton aceptar = new JButton("Aceptar");
       JCheckBox masculino = new JCheckBox("Masculino");
       JCheckBox femenino = new JCheckBox("Femenino");       
       cambiarPreferencia.add(masculino);
       cambiarPreferencia.add(femenino);
       cambiarPreferencia.add(aceptar);
       dialog.add(cambiarPreferencia);
       dialog.setVisible(true);
       if(masculino.isSelected()){
           cambiaGenero = Genero.HOMBRE;
           LabelSexo.setText("Masculino");
       }else if (femenino.isSelected()){
           cambiaGenero = Genero.MUJER;
           LabelSexo.setText("Femenino");
       }
       
    }//GEN-LAST:event_ButtonCambiarSexoActionPerformed

    private void ButtonEliminarAficionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarAficionActionPerformed
       listaModel.remove(ListaAficiones.getSelectedIndex()); 
    }//GEN-LAST:event_ButtonEliminarAficionActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        cancelar = true;
        // borra las aficiones que antes estaban
        listaModel.removeAllElements();
        ListaAficiones.removeAll();
        // borra el area de texto
        textAreaDescripcion.setText(null);        
        this.setVisible(false);
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonCambiarPreferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarPreferenciaActionPerformed
       JDialog dialog = new JDialog(this, true);
       dialog.setBounds(500, 60, 350, 80);
       JPanel cambiarPreferencia = new JPanel();
       JCheckBox hombres = new JCheckBox("Hombres");
       JCheckBox mujeres = new JCheckBox("Mujeres");
       JCheckBox ambos = new JCheckBox("Ambos");
       JButton aceptar = new JButton("Aceptar");
       cambiarPreferencia.add(hombres);
       cambiarPreferencia.add(mujeres);
       cambiarPreferencia.add(ambos);
       cambiarPreferencia.add(aceptar);
       dialog.add(cambiarPreferencia);
       dialog.setVisible(true);
       
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {       
                if(hombres.isSelected()){
                    cambiaPreferencia = Genero.HOMBRE;
                    LabelBusca.setText("Hombres");
                } else if (mujeres.isSelected()){
                    cambiaPreferencia = Genero.MUJER;
                    LabelBusca.setText("Mujeres");
                }else{
                    cambiaPreferencia = Genero.AMBOS;
                    LabelBusca.setText("Ambos");
                }

                 System.out.println(cambiaPreferencia);
                 dialog.setVisible(false);
            }
        });
    }//GEN-LAST:event_ButtonCambiarPreferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EdicionUsuario dialog = new EdicionUsuario(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddAficion;
    private javax.swing.JButton ButtonCambiarAvatar;
    private javax.swing.JButton ButtonCambiarContraseña;
    private javax.swing.JButton ButtonCambiarFechaNacimiento;
    private javax.swing.JButton ButtonCambiarNombre;
    private javax.swing.JButton ButtonCambiarPreferencia;
    private javax.swing.JButton ButtonCambiarSexo;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonEditarAficion;
    private javax.swing.JButton ButtonEliminarAficion;
    private javax.swing.JButton ButtonGuardarCambios;
    private javax.swing.JLabel LabelBusca;
    private javax.swing.JLabel LabelEdad;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelSexo;
    private javax.swing.JList<String> ListaAficiones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaDescripcion;
    // End of variables declaration//GEN-END:variables
}
