/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.model.Usuario;
import com.toedter.calendar.JDateChooser;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jhersy
 */
public class ModificarPerfilUsuario extends javax.swing.JFrame {
    /**
     * Creates new form PerfilUsuario
     */
    private Usuario user;
    private String cambiaNombre;
    private File cambiaAvatar;
    private String cambiaSexo;
    private DefaultListModel listaModel = new DefaultListModel();
    private List<String> aficiones = new ArrayList<String>();
    public ModificarPerfilUsuario(boolean editar, Usuario user) {
        initComponents();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelNombre = new javax.swing.JLabel();
        LabelEdad = new javax.swing.JLabel();
        ButtonCambiarNombre = new javax.swing.JButton();
        ButtonCambiarFechaNacimiento = new javax.swing.JButton();
        ButtonCambiarAvatar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaAficiones = new javax.swing.JList<>();
        ButtonAddAficion = new javax.swing.JButton();
        ButtonEliminarAficion = new javax.swing.JButton();
        ButtonEditarAficion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelSexo = new javax.swing.JLabel();
        LabelBusca = new javax.swing.JLabel();
        ButtonCambiarSexo = new javax.swing.JButton();
        ButtonCambiarPreferencia = new javax.swing.JButton();
        ButtonCambiarContraseña = new javax.swing.JButton();
        ButtonGuardarCambios = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelNombre.setText("Nombre");

        LabelEdad.setText("Edad");

        ButtonCambiarNombre.setText("Cambiar nombre");
        ButtonCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarNombreActionPerformed(evt);
            }
        });

        ButtonCambiarFechaNacimiento.setText("Cambiar fecha de nacimiento");
        ButtonCambiarFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarFechaNacimientoActionPerformed(evt);
            }
        });

        ButtonCambiarAvatar.setText("Cambiar avatar");
        ButtonCambiarAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarAvatarActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripción");

        textAreaDescripcion.setColumns(20);
        textAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(textAreaDescripcion);

        jLabel3.setText("Aficiones");

        ListaAficiones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaAficiones);

        ButtonAddAficion.setText("Añadir Afición");
        ButtonAddAficion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddAficionActionPerformed(evt);
            }
        });

        ButtonEliminarAficion.setText("Eliminar seleccionada");

        ButtonEditarAficion.setText("Editar seleccionada");

        jLabel4.setText("Sexo: ");

        jLabel5.setText("Busca: ");

        LabelSexo.setText("Masculino");

        LabelBusca.setText("Mujeres");

        ButtonCambiarSexo.setText("Cambiar sexo");
        ButtonCambiarSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarSexoActionPerformed(evt);
            }
        });

        ButtonCambiarPreferencia.setText("Cambiar preferencia");
        ButtonCambiarPreferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarPreferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelBusca))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonEliminarAficion, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(ButtonEditarAficion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCambiarSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCambiarPreferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonAddAficion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelSexo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonCambiarAvatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCambiarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCambiarFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(ButtonCambiarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCambiarFechaNacimiento)
                    .addComponent(LabelEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCambiarAvatar)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(ButtonAddAficion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEliminarAficion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEditarAficion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCambiarSexo)
                    .addComponent(jLabel4)
                    .addComponent(LabelSexo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCambiarPreferencia)
                    .addComponent(jLabel5)
                    .addComponent(LabelBusca))
                .addContainerGap())
        );

        ButtonCambiarContraseña.setText("Cambiar contraseña");

        ButtonGuardarCambios.setText("Guardar cambios");
        ButtonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarCambiosActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ButtonCambiarContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonGuardarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCambiarContraseña)
                    .addComponent(ButtonGuardarCambios)
                    .addComponent(ButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarNombreActionPerformed
        // TODO add your handling code here:
        JFrame cambiarNombre = new JFrame("Editar nombre");
        cambiaNombre = JOptionPane.showInputDialog(cambiarNombre, "Introduce nuevo nombre");
        System.out.println(cambiaNombre);
    }//GEN-LAST:event_ButtonCambiarNombreActionPerformed

    private void ButtonCambiarAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarAvatarActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Cambiar avatar");
        frame.setBounds(0, 0, 600, 400);
        JPanel panel = new JPanel();
        JFileChooser avatar = new JFileChooser();
        avatar.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.JPG", "jpg");
        avatar.setFileFilter(filtro);
        panel.add(avatar);
        JButton aceptar = new JButton("Aceptar");
        panel.add(aceptar);
        frame.add(panel);
        frame.setVisible(true);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiaAvatar = avatar.getSelectedFile();
                System.out.println(cambiaAvatar);
                frame.setVisible(false);
            }
        });
        
    }//GEN-LAST:event_ButtonCambiarAvatarActionPerformed

    private void ButtonCambiarSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarSexoActionPerformed
       JFrame frame = new JFrame("Editar sexo");
       frame.setBounds(500, 60, 350, 80);
       JPanel cambiarPreferencia = new JPanel();
       JButton aceptar = new JButton("Aceptar");
       JCheckBox masculino = new JCheckBox("Masculino");
       JCheckBox femenino = new JCheckBox("Femenino");
       cambiarPreferencia.add(masculino);
       cambiarPreferencia.add(femenino);
       cambiarPreferencia.add(aceptar);
       frame.add(cambiarPreferencia);
       frame.setVisible(true);
    }//GEN-LAST:event_ButtonCambiarSexoActionPerformed

    private void ButtonCambiarFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarFechaNacimientoActionPerformed
        JFrame frame = new JFrame("Editar fecha de nacimiento");
        frame.setBounds(0, 0, 400, 150);
        JPanel panel = new JPanel();
        JDateChooser fecha = new JDateChooser();
        panel.add(fecha);
        JButton aceptar = new JButton("Aceptar");
        panel.add(aceptar);
        frame.add(panel);
        frame.setVisible(true);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date date = fecha.getDate();
                System.out.println(date);
                frame.setVisible(false);
            }
        });
    }//GEN-LAST:event_ButtonCambiarFechaNacimientoActionPerformed

    private void ButtonCambiarPreferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarPreferenciaActionPerformed
        // TODO add your handling code here:
        // tiene que ser solo dos o tres opciones opciones
       JFrame frame = new JFrame("Editar preferencia");
       frame.setBounds(500, 60, 350, 80);
       JPanel cambiarPreferencia = new JPanel();
       JCheckBox hombres = new JCheckBox("Hombres");
       JCheckBox mujeres = new JCheckBox("Mujeres");
       JCheckBox ambos = new JCheckBox("Ambos");
       JButton aceptar = new JButton("Aceptar");
       cambiarPreferencia.add(hombres);
       cambiarPreferencia.add(mujeres);
       cambiarPreferencia.add(ambos);
       cambiarPreferencia.add(aceptar);
       frame.add(cambiarPreferencia);
       frame.setVisible(true);
              
    }//GEN-LAST:event_ButtonCambiarPreferenciaActionPerformed

    private void ButtonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarCambiosActionPerformed
        // Los cambios no se realizan en la bd hasta que llegue aquí
        
        
        
        
    }//GEN-LAST:event_ButtonGuardarCambiosActionPerformed

    private void ButtonAddAficionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddAficionActionPerformed
        // TODO add your handling code here:
        JFrame addAficion = new JFrame("Añadir afición");
        String nuevaAficion = JOptionPane.showInputDialog(addAficion, "Introduce nueva afición: ");
        aficiones.add(nuevaAficion);
        listaModel.addElement(nuevaAficion);
        ListaAficiones.setModel(listaModel);
        System.out.println(nuevaAficion);
        
    }//GEN-LAST:event_ButtonAddAficionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        Usuario user = new Usuario();
        boolean mostrar = true;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPerfilUsuario(mostrar, user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddAficion;
    private javax.swing.JButton ButtonCambiarAvatar;
    private javax.swing.JButton ButtonCambiarContraseña;
    private javax.swing.JButton ButtonCambiarFechaNacimiento;
    private javax.swing.JButton ButtonCambiarNombre;
    private javax.swing.JButton ButtonCambiarPreferencia;
    private javax.swing.JButton ButtonCambiarSexo;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonEditarAficion;
    private javax.swing.JButton ButtonEliminarAficion;
    private javax.swing.JButton ButtonGuardarCambios;
    private javax.swing.JLabel LabelBusca;
    private javax.swing.JLabel LabelEdad;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelSexo;
    private javax.swing.JList<String> ListaAficiones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaDescripcion;
    // End of variables declaration//GEN-END:variables
}
